### ISSUE TITLE
Can I use this setting to service emqttd for clients outside of AWS?

### ISSUE THREAD

**Issue by jngbng** [felipejfc/emqtt-k8s#2]
https://groups.google.com/forum/#!topic/kubernetes-users/B13qXsyYC8A

I wonder whether these is a way to expose a headless service to the world.

**Comment by felipejfc** [comment]
sure, you only need to create another service to expose it.

```
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: emqtt
    name: emqtt-ext
    namespace: emqtt
  spec:
    ports:
    - name: mqttssl
      nodePort: 31549
      port: 8883
      protocol: TCP
      targetPort: 1883
    selector:
      app: emqtt
    type: LoadBalancer
```

so you will have 2 services, a headless one for the StatefulSet and another one for exposing the pods ports to the outside world :)

reopen the issue if you need further help.
